AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - '*.gemspec'
    - 'vendor/**/*'
    - 'bin/*'
  NewCops: enable  

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*