AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - '*.gemspec'
    - 'vendor/**/*'
    - 'bin/*'
  NewCops: enable  

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - lib/checkers/ai/engine/**/*

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - lib/checkers/ai/engine/**/*

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - lib/checkers/ai/engine/**/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - lib/checkers/ai/engine/**/*