#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'checkers'

window = Window.new
window.set(title: 'Checkers')

state = Checkers::Game::State.new(:human)
ai = Checkers::AI::Engine::Minmax.new
game_engine = Checkers::Game::Engine.new(state, ai)
scene = Checkers::GUI::Scene.new(state, game_engine)

window.on :mouse_up do |event|
  x = event.x
  y = event.y

  scene.handle_click(x, y) if event.button == :left
end

animating = nil

window.update do
  if animating.nil?
    unless scene.animation_queue.empty?
      animating = scene.animation_queue.pop
      animating.call
    end
  elsif animating.finished == false
    animating.call
  else
    animating = nil
  end
end

window.show
