#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'checkers'

state = Checkers::Game::State.new(:human)
scene = Checkers::GUI::Scene.new(state)
ai = Checkers::AI::Engine::Minmax.new
game_engine = Checkers::Game::Engine.new(state, ai)

on :mouse_up do |event|
  x = event.x
  y = event.y

  scene.handle_click(x, y) if event.button == :left
end

show
